# Generated by Django 5.1.5 on 2025-01-25 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('movie_id', models.IntegerField()),
                ('theater_id', models.IntegerField()),
                ('seat_number', models.CharField(max_length=10)),
                ('time', models.DateTimeField()),
            ],
        ),
    ]
